[package]
name = "bequest-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.8"
spinners = "4.1.1"
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk" }
tokio = { version = "1.2", features = ["full"] }
anyhow = "1.0"
